### ISSUE TITLE
Policy config on EdgeOS (Edgerouter X)

### ISSUE THREAD

**Issue by jbialy** [Control-D-Inc/ctrld#134]
Hey Folks, thanks for creating this great piece of software! 😄 

I've been trying to get ctrld working on an Edgerouter X (running firmware 2.0.9-hotfix.7). All 2.x.x releases use Debian 9 (Stretch). 

I have a pretty basic config which I would expect to work, however, it seems like the policy rules are not being considered at all, and all traffic is being sent to `upstream.0`. Here's the config that I've been using:

```toml
[service]
  log_level = "info"
  log_path = "/var/log/ctrld.log"

[listener]
  [listener.0]
    ip = '0.0.0.0'
    port = 5354

    [listener.0.policy]
      name = 'Main Policy'
      networks = [
        {'network.0' = ['upstream.0']},
        {'network.1' = ['upstream.0']}
      ]
      macs = [
        {'b0:be:83:2d:c6:50' = ['upstream.1']}
      ]

[network]
  [network.0]
    name = 'LAN'
    cidrs = ['192.168.1.0/25']

  [network.1]
    name = 'LAN-IoT'
    cidrs = ['10.10.10.0/27']

[upstream]
  [upstream.0]
    name = 'Cloudflare'
    type = 'dot'
    endpoint = '1.1.1.1:853'
    timeout = 5000
  [upstream.1]
    name = 'SmartDNS Proxy MTL'
    type = 'legacy'
    endpoint = '169.54.78.85'
    timeout = 5000
```

Looking at the config, I would expect DNS requests from both networks to go out `upstream.0` and for the specified mac address to go out on `upstream.1`. However, when testing this from the machine with the mac address specified, and looking at the ctrld logs, there are never any requests hitting upstream.1. 

Here's are snippets from the logs:

```
$ head /var/log/ctrld.log
{"level":"info","time":"2024-01-19T16:30:13Z.757","message":"starting ctrld v1.3.3"}
{"level":"info","time":"2024-01-19T16:30:13Z.767","message":"os: linux 4.14.54-UBNT"}
{"level":"info","bootstrap_ip":"1.1.1.1","time":"2024-01-19T16:30:14Z.584","message":"using bootstrap IP for upstream.0"}
{"level":"info","bootstrap_ip":"169.54.78.85","time":"2024-01-19T16:30:14Z.585","message":"using bootstrap IP for upstream.1"}
{"level":"warn","time":"2024-01-19T16:30:14Z.627","message":"no default route IP found"}
{"level":"info","time":"2024-01-19T16:30:14Z.629","message":"starting DNS server on listener.0: 0.0.0.0:5354"}
{"level":"info","time":"2024-01-19T16:30:21Z.229","message":"[fbf13a] QUERY: 127.0.0.1:39005 (gatekeepr) -> listener.0: A detectportal.firefox.com"}
{"level":"info","time":"2024-01-19T16:30:21Z.234","message":"[f84262] QUERY: 127.0.0.1:48816 (gatekeepr) -> listener.0: PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa"}
{"level":"info","time":"2024-01-19T16:30:21Z.748","message":"[d907b4] QUERY: 127.0.0.1:48816 (gatekeepr) -> listener.0: PTR lb._dns-sd._udp.0.1.168.192.in-addr.arpa"}
{"level":"info","time":"2024-01-19T16:30:21Z.908","message":"[f84262] REPLY: upstream.0 -> 127.0.0.1:48816 (gatekeepr): NXDOMAIN"}
```

After making a request from machine with mac addrs `b0:be:83:2d:c6:50`, I don't see any hits on upstream.1:

```
cat /var/log/ctrld.log | grep upstream.1
{"level":"info","bootstrap_ip":"169.54.78.85","time":"2024-01-19T16:30:14Z.585","message":"using bootstrap IP for upstream.1"}
```

Instead of using the `macs` policy block, I also tried to use `networks: []` instead, and use the source IP of the machine, i.e. `192.168.1.44/32` but the results are no different. It seems that the policy evaluation doesn't happen at all? 

ctrld is obviously working and routing all the traffic to the default upstream.0 however, so this is very strange. I've even checked to make sure that `/etc/dnsmasq.d/dnsmasq-zzz-ctrld.conf` is being created when ctrld is active, and everything seems to check out fine!

Hoping for a bit of help here, has anyone else seen this when testing on their device? Is it the config? Am I missing something? I can provide more detailed logs if that helps!

Thanks and much appreciated!
