### ISSUE TITLE
Control D + NextDNS + Legacy DNS Resolver

### ISSUE THREAD

**Issue by mrkhachaturov** [Control-D-Inc/ctrld#190]
Hi, 
I am trying to configure setup where NextDNS would work as failover vor Control D ( not sure it will happen, but as I have already paid for NextDNS i will keep it yet) also I need to forward some domain names to legacy DNS Servers installed in my homelab.
Is this configuration correct?
ChatGPT is telling that some options for upstream selection policy are available,  I am not sure cause didn`t find such info in documantation. 
***
## Upstream Selection Policy
By default, when multiple upstreams are specified for a rule, ctrld will:

Send the query to all specified upstreams in parallel.
Return the first valid response it receives.
This behavior ensures faster responses and redundancy.
If you prefer a different upstream selection strategy, you can specify it. For example, to use failover instead of parallel queries:
```toml
[listener.0.policy]  
  # ... other settings ...  
  options = { upstream_selection = 'failover' }  
```
Available options for upstream_selection are:

**parallel**: Send query to all upstreams and use the first response.
**failover**: Try upstreams one at a time in order; proceed to the next if the previous fails.
**random**: Randomly select an upstream for each query.

***
My configuration:
```toml
[service]
    log_level = "info"
    log_path = ""
    cache_enable = true
    cache_size = 4096
    cache_ttl_override = 60
    cache_serve_stale = true

[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Everyone"

[upstream.0]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/xxxxx"
    name = "Control D"
    timeout = 5000
    type = "doh3"
    ip_stack = "split"

[upstream.1]
    endpoint = "https://dns.nextdns.io/xxxxx/RT01"
    name = "NextDNS"
    timeout = 5000
    type = "doh3"
    ip_stack = "split"

[upstream.2]
    endpoint = "10.2.0.11:53"
    name = "DC01"
    timeout = 5000
    type = "legacy"
    ip_stack = "v4"

[upstream.3]
    endpoint = "10.5.5.2:53"
    name = "DC02"
    timeout = 5000
    type = "legacy"
    ip_stack = "v4"


[listener.0]
    ip = "127.0.0.1"
    port = 53

[listener.0.policy]
    name = "Default Policy"
    failover_rcodes = ["NXDOMAIN", "SERVFAIL"]
    networks = [
        {"network.0" = ["upstream.0", "upstream.1"]},
    ]
    rules = [
        { "trusted.cooldomain.net" = ["upstream.0", "upstream.1"]},
        { "*.link.cooldomain.net" = ["upstream.0", "upstream.1"]},
        { "cooldomain.net" = ["upstream.2", "upstream.3"]},  
        { "*.cooldomain.net" = ["upstream.2", "upstream.3"]},
    ]
```
