### ISSUE TITLE
ctrld not replace /etc/resolv.conf

### ISSUE THREAD

**Issue by malikshi** [Control-D-Inc/ctrld#70]
```toml
[service]
    log_level = "info"
    log_path = "/var/log/ctrld.log"
    cache_enable = true
    cache_size = 16777216
    cache_ttl_override = 10

[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Public"

[listener.0]
    ip = "0.0.0.0"
    port = 53

[listener.0.policy]
    name = 'Fallback'
    networks = [
        {"network.0" = ["upstream.0", "upstream.1", "upstream.2", "upstream.3"]}
    ]

[upstream.0]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/DNS_CODE"
    name = "Control D - DOH"
    timeout = 200
    type = "doh3"
    ip_stack = "split"

[upstream.1]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/DNS_CODE"
    name = "Control D - DOH3"
    timeout = 200
    type = "doh"
    ip_stack = "split"

[upstream.2]
    bootstrap_ip = "76.76.2.22"
    endpoint = "DNS_CODE.dns.controld.com"
    name = "Controld D - DOQ"
    timeout = 200
    type = "doq"
    ip_stack = "split"

[upstream.3]
    bootstrap_ip = "76.76.2.22"
    endpoint = "DNS_CODE.dns.controld.com"
    name = "Controld D - DOT"
    timeout = 200
    type = "dot"
    ip_stack = "split"
```

ctrld service start -c /path-to-file/config.toml

checking cat /etc/resolv.conf
```
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 208.67.222.222
nameserver 1.1.1.1
```

command without service
ctrld start -c /path-to-file/config.toml
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 127.0.0.1
